 databases:
  - name: restapi
    databaseName: restapi_zddj
    user: restapi_zddj_user

services:
  - type: web
    name: restapi
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: restapi_zddj
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false